//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace canteenVLU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOOD()
        {
            this.MENUs = new HashSet<MENU>();
        }
    
        public int ID { get; set; }
        public string FOOD_CODE { get; set; }
        public string FOOD_NAME { get; set; }
        public int CATEGORY_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public int PRICE { get; set; }
        public string IMAGE_URL { get; set; }
        public bool STATUS { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU> MENUs { get; set; }
    }
}
